version: '3.8'

services:
     web:
       image: nginx:latest
       restart: always
       ports:
           - "80:80"
       volumes:
           - ./app:/app
           - ./conf.d:/etc/nginx/conf.d
       networks:
           - game-network

     php-fpm:
       build: .
       restart: always
       volumes:
           - ./app:/app
       expose:
           - 9000
       networks:
           - game-network

     mysql_db:
       image: mysql:latest
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
       volumes:
         - game-php_game-db:/var/lib/mysql
       networks:
           - game-network

     phpmyadmin:
       image: phpmyadmin:latest
       restart: always
       ports:
         - 9001:80
       environment:
         - PMA_ARBITRARY=1
       networks:
           - game-network

volumes:
  game-php_game-db:
    external: true

networks:
     game-network:
